from __future__ import annotations

from pdomain_pgdp_measure.alignment_models import (
    ALIGNMENT_ALGORITHM_VERSION,
    ALIGNMENT_SCHEMA_VERSION,
    CONFIDENCE_KIND,
    AlignmentDiagnostic,
    AlignmentOperation,
    AlignmentReport,
    PageAlignment,
    ProjectAlignment,
    WireFormattingSpan,
    WireLineCandidate,
    WireSourceLine,
    WireStyleRun,
)
from pdomain_pgdp_measure.alignment_review import (
    MINIMUM_ACCEPTED_PAGES_PER_BOOK,
    BookYield,
    PageClassification,
    ReviewCategory,
    ReviewCounts,
    ReviewedLine,
    ReviewGateFailure,
    ReviewGateResult,
    ReviewLedger,
    ReviewPage,
    ReviewSummary,
    classify_page,
    render_alignment_overlay,
    render_line_typography_overlay,
    summarize_book_yield,
    summarize_review,
    validate_review_gate,
)
from pdomain_pgdp_measure.features import extract_page_features, score_page
from pdomain_pgdp_measure.models import (
    CorpusSummary,
    Diagnostic,
    PageFeatures,
    PageScore,
    RankedPage,
    RankedProject,
    RankingLimits,
    RankingReport,
)
from pdomain_pgdp_measure.ordering import natural_page_key
from pdomain_pgdp_measure.profile_models import (
    CoordinateFrame,
    Estimate,
    InkBand,
    PageMeasurement,
    ProfileDiagnostic,
    ProfileReport,
    ProjectProfile,
)
from pdomain_pgdp_measure.ranking import rank_corpus
from pdomain_pgdp_measure.report import write_report
from pdomain_pgdp_measure.typography import ProvenanceError, build_typography_report
from pdomain_pgdp_measure.typography_models import (
    DEFAULT_EVIDENCE_PAGES_PER_BOOK,
    LATENT_KEY_DENYLIST,
    TYPOGRAPHY_ALGORITHM_VERSION,
    TYPOGRAPHY_SCHEMA_VERSION,
    BookTypography,
    LineTypography,
    PageTypography,
    StyleTypography,
    TypographyReport,
    WordTypography,
    find_latent_discipline_violations,
)
from pdomain_pgdp_measure.typography_pooling import (
    BOOK_POOLING_METHOD,
    PAGE_POOLING_METHOD,
    BookPooling,
    PagePooling,
    SkewSummary,
    pool_book,
    pool_page,
)

__all__ = [
    "ALIGNMENT_ALGORITHM_VERSION",
    "ALIGNMENT_SCHEMA_VERSION",
    "BOOK_POOLING_METHOD",
    "CONFIDENCE_KIND",
    "DEFAULT_EVIDENCE_PAGES_PER_BOOK",
    "LATENT_KEY_DENYLIST",
    "MINIMUM_ACCEPTED_PAGES_PER_BOOK",
    "PAGE_POOLING_METHOD",
    "TYPOGRAPHY_ALGORITHM_VERSION",
    "TYPOGRAPHY_SCHEMA_VERSION",
    "AlignmentDiagnostic",
    "AlignmentOperation",
    "AlignmentReport",
    "BookPooling",
    "BookTypography",
    "BookYield",
    "CoordinateFrame",
    "CorpusSummary",
    "Diagnostic",
    "Estimate",
    "InkBand",
    "LineTypography",
    "PageAlignment",
    "PageClassification",
    "PageFeatures",
    "PageMeasurement",
    "PagePooling",
    "PageScore",
    "PageTypography",
    "ProfileDiagnostic",
    "ProfileReport",
    "ProjectAlignment",
    "ProjectProfile",
    "ProvenanceError",
    "RankedPage",
    "RankedProject",
    "RankingLimits",
    "RankingReport",
    "ReviewCategory",
    "ReviewCounts",
    "ReviewGateFailure",
    "ReviewGateResult",
    "ReviewLedger",
    "ReviewPage",
    "ReviewSummary",
    "ReviewedLine",
    "SkewSummary",
    "StyleTypography",
    "TypographyReport",
    "WireFormattingSpan",
    "WireLineCandidate",
    "WireSourceLine",
    "WireStyleRun",
    "WordTypography",
    "build_typography_report",
    "classify_page",
    "extract_page_features",
    "find_latent_discipline_violations",
    "natural_page_key",
    "pool_book",
    "pool_page",
    "rank_corpus",
    "render_alignment_overlay",
    "render_line_typography_overlay",
    "score_page",
    "summarize_book_yield",
    "summarize_review",
    "validate_review_gate",
    "write_report",
]
